### ISSUE TITLE
Получаю ошибку HTTPSConnectionPool

### ISSUE THREAD

**Issue by 31onMusk** [resppl/TelegramStealer#1]
При запуске я получаю ошибку HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /botТОКЕНБОТА/sendDocument?chat_id=МойЧатАйди (Caused by SSLError(SSLWantWriteError(3, 'The operation did not complete (write) (_ssl.c:2396)')))

Как исправить? Также я изменил папку с Telegram Desktop UWP на Telegram Desktop

Я использую версию скрипта на Telebot.

**Comment by resppl** [comment]
Проблема возникает в результате некорректного подключения. Проверьте правильность введенных данных бота API Telegram в переменной "BOT_TOKEN".
